// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"usm/internal/biz/usecase/account"
	"usm/internal/conf"
	"usm/internal/data"
	"usm/internal/server"
	account2 "usm/internal/service/account"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	usecase := account.NewUsecase(userRepo)
	service := account2.NewService(usecase, logger)
	httpServer := server.NewHTTPServer(confServer, service, logger)
	grpcServer := server.NewGRPCServer(confServer, service, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
